
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Label TitleLabel;

	private global::Gtk.Label OAuthLabel;

	private global::Gtk.Entry entry1;

	private global::Gtk.Button StartButton;

	private global::Gtk.Button StopButton;

	private global::Gtk.Label StatusLabel;

	private global::Gtk.Entry entry3;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TreeView UserList;

	private global::Gtk.Button AddUserButton;

	private global::Gtk.Button RemoveUserButton;

	private global::Gtk.CheckButton AutoStartCheckbox;

	private global::Gtk.ComboBox GenerationBox;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Mr. Fuji Bot");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.TitleLabel = new global::Gtk.Label();
		this.TitleLabel.Name = "TitleLabel";
		this.TitleLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Mr. Fuji Bot Control Panel");
		this.fixed1.Add(this.TitleLabel);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.TitleLabel]));
		w1.X = 15;
		w1.Y = 15;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.OAuthLabel = new global::Gtk.Label();
		this.OAuthLabel.Name = "OAuthLabel";
		this.OAuthLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Twitch Chat OAuth Password:");
		this.fixed1.Add(this.OAuthLabel);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.OAuthLabel]));
		w2.X = 15;
		w2.Y = 45;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry1 = new global::Gtk.Entry();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.WidthChars = 40;
		this.fixed1.Add(this.entry1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry1]));
		w3.X = 195;
		w3.Y = 40;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.StartButton = new global::Gtk.Button();
		this.StartButton.WidthRequest = 100;
		this.StartButton.CanFocus = true;
		this.StartButton.Name = "StartButton";
		this.StartButton.UseUnderline = true;
		this.StartButton.Label = global::Mono.Unix.Catalog.GetString("Start");
		this.fixed1.Add(this.StartButton);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.StartButton]));
		w4.X = 15;
		w4.Y = 75;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.StopButton = new global::Gtk.Button();
		this.StopButton.WidthRequest = 100;
		this.StopButton.CanFocus = true;
		this.StopButton.Name = "StopButton";
		this.StopButton.UseUnderline = true;
		this.StopButton.Label = global::Mono.Unix.Catalog.GetString("Stop");
		this.fixed1.Add(this.StopButton);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.StopButton]));
		w5.X = 120;
		w5.Y = 75;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.StatusLabel = new global::Gtk.Label();
		this.StatusLabel.Name = "StatusLabel";
		this.StatusLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Status:");
		this.fixed1.Add(this.StatusLabel);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.StatusLabel]));
		w6.X = 240;
		w6.Y = 83;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry3 = new global::Gtk.Entry();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.Text = global::Mono.Unix.Catalog.GetString("Stopped");
		this.entry3.IsEditable = false;
		this.entry3.WidthChars = 10;
		this.fixed1.Add(this.entry3);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry3]));
		w7.X = 285;
		w7.Y = 79;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.UserList = new global::Gtk.TreeView();
		this.UserList.WidthRequest = 150;
		this.UserList.CanFocus = true;
		this.UserList.Name = "UserList";
		this.UserList.FixedHeightMode = true;
		this.GtkScrolledWindow.Add(this.UserList);
		this.fixed1.Add(this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
		w9.X = 25;
		w9.Y = 131;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.AddUserButton = new global::Gtk.Button();
		this.AddUserButton.WidthRequest = 120;
		this.AddUserButton.CanFocus = true;
		this.AddUserButton.Name = "AddUserButton";
		this.AddUserButton.UseUnderline = true;
		this.AddUserButton.Label = global::Mono.Unix.Catalog.GetString("Add User");
		this.fixed1.Add(this.AddUserButton);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.AddUserButton]));
		w10.X = 197;
		w10.Y = 133;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.RemoveUserButton = new global::Gtk.Button();
		this.RemoveUserButton.WidthRequest = 120;
		this.RemoveUserButton.CanFocus = true;
		this.RemoveUserButton.Name = "RemoveUserButton";
		this.RemoveUserButton.UseUnderline = true;
		this.RemoveUserButton.Label = global::Mono.Unix.Catalog.GetString("Remove User");
		this.fixed1.Add(this.RemoveUserButton);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.RemoveUserButton]));
		w11.X = 197;
		w11.Y = 160;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.AutoStartCheckbox = new global::Gtk.CheckButton();
		this.AutoStartCheckbox.CanFocus = true;
		this.AutoStartCheckbox.Name = "AutoStartCheckbox";
		this.AutoStartCheckbox.Label = global::Mono.Unix.Catalog.GetString("Auto-start");
		this.AutoStartCheckbox.DrawIndicator = true;
		this.AutoStartCheckbox.UseUnderline = true;
		this.fixed1.Add(this.AutoStartCheckbox);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.AutoStartCheckbox]));
		w12.X = 381;
		w12.Y = 79;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GenerationBox = global::Gtk.ComboBox.NewText();
		this.GenerationBox.AppendText(global::Mono.Unix.Catalog.GetString("Generation 1"));
		this.GenerationBox.AppendText(global::Mono.Unix.Catalog.GetString("Generation 2"));
		this.GenerationBox.AppendText(global::Mono.Unix.Catalog.GetString("Generation 3"));
		this.GenerationBox.AppendText(global::Mono.Unix.Catalog.GetString("Generation 4"));
		this.GenerationBox.AppendText(global::Mono.Unix.Catalog.GetString("Generation 5"));
		this.GenerationBox.AppendText(global::Mono.Unix.Catalog.GetString("Generation 6"));
		this.GenerationBox.AppendText(global::Mono.Unix.Catalog.GetString("Generation 7"));
		this.GenerationBox.WidthRequest = 125;
		this.GenerationBox.CanDefault = true;
		this.GenerationBox.Name = "GenerationBox";
		this.GenerationBox.Active = 6;
		this.fixed1.Add(this.GenerationBox);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GenerationBox]));
		w13.X = 349;
		w13.Y = 135;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 506;
		this.DefaultHeight = 232;
		this.GenerationBox.HasDefault = true;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
